### ISSUE TITLE
Please remove x-revision: header from Cabal file

### ISSUE THREAD

**Issue by peti** [alephcloud/hs-stm-queue-extras#2]
Your cabal file contains an `x-revision` header: https://github.com/alephcloud/hs-stm-queue-extras/blob/master/stm-queue-extras.cabal#L11. That header has a special meaning for Hackage, i.e. it's set when a package is edited on-line to distinguish different versions. With that header set, some tools (like `cabal2nix`) will assume that there is an edited revision "1" of `stm-queue-extras` and try to download it, when in fact no such revision exists.

**Comment by peti** [comment]
Related: https://github.com/haskell/hackage-server/issues/337

**Comment by peti** [comment]
Ping?

**Comment by jonsterling** [comment]
Hello, sorry I lost track of this. I will address it today.

JMS

**Comment by jonsterling** [comment]
@peti I have removed the line from the cabal file. Please let me know if you need me to release a new version of the package to Hackage, or if that was sufficient. Sorry again for losing track of this ticket!

**Comment by peti** [comment]
Thank you for the fix! A new release on Hackage would be great.

**Comment by jonsterling** [comment]
Sure! I'll push a new minor release to hackage today.

**Comment by jonsterling** [comment]
Done.
